from .attacke_service import get_most_attack_types
from .region_service import calculate_average_victims_per_event_by_region, calculate_percent_change
from .terror_groups_service import get_most_damaging_terror_groups, calculate_most_active_groups
from .target_type_service import calculate_groups_with_shared_targets